on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A sample job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run scan
        id: scan
        uses: ankurv3rma/ts-action-test@main
        with:
          api: ${{ secrets.ENDOR_API }}
          api_key: ${{ secrets.ENDOR_API_KEY }}
          api_secret: ${{ secrets.ENDOR_API_SECRET }}
          scan_summary_output_type: "json"
          namespace: "testing-tenant"
          
      # Use the output from the `scan` step
      - name: Get the output
        run: echo ${{ steps.scan.outputs.result }} > ${{ github.workspace }}/result.json

      # Upload the result as an artifact
      - name: Upload the result artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: results
          path: ${{ github.workspace }}/result.json
