on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A sample job
    env:
      # 7 GiB by default on GitHub, setting this to 16 GiB
      NODE_OPTIONS: --max-old-space-size=16384
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run scan
        id: scan
        uses: ankurv3rma/ts-action-test@main
        with:
          api: ${{ secrets.ENDOR_API }}
          api_key: ${{ secrets.ENDOR_API_KEY }}
          api_secret: ${{ secrets.ENDOR_API_SECRET }}
          scan_summary_output_type: "json"
          namespace: "testing-tenant"
#           additional_args: "--output-filter=low"
      
      - name: Print Output
        run: echo "The result1 was ${{ steps.scan.outputs.result1 }}"
        
      - name: Print Output
        run: echo "The result2 was ${{ steps.scan.outputs.result2 }}"
        
      - name: Print Output
        run: echo "The result3 was ${{ steps.scan.outputs.result3 }}"
        
      - name: Print Output
        run: echo "The result4 was ${{ steps.scan.outputs.result4 }}"
        
      - name: Print Output
        run: echo "The result5 was ${{ steps.scan.outputs.result5 }}"
        
      - name: Print Output
        run: echo "The result6 was ${{ steps.scan.outputs.result6 }}"
        
      - name: Print Output
        run: echo "The result7 was ${{ steps.scan.outputs.result7 }}"
        
      - name: Print Output
        run: echo "The result8 was ${{ steps.scan.outputs.result8 }}"
        
      - name: Print Output
        run: echo "The result9 was ${{ steps.scan.outputs.result9 }}"
      
          
#       - name: devops-actions/json-to-file@v1.0.0
#         with:
#           json: ${{ steps.scan.outputs.result }}
#           filename: "result.json"

      # Upload the result as an artifact
#       - name: Upload the result artifact
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: results
#           path: ${{ github.workspace }}/result.json
