on: [push, workflow_dispatch]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A sample job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          
      - name: Run scan
        id: scan
        uses: endorlabs/ts-action-test@main
        with:
          api: ${{ secrets.ENDOR_API }}
          api_key: ${{ secrets.ENDOR_API_KEY }}
          api_secret: ${{ secrets.ENDOR_API_SECRET }}
          scan_summary_output_type: "json"
          namespace: "testing-tenant"
